sudo: required

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t rehan/docker-react .

script:
  - docker run -e CI=true rehan/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  name: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-485298220100"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"